version: "3.0"

http:
  address: "0.0.0.0:8080"
  static:
    dir: "public"
    forbid: [".htaccess", "*.json", "*.py"]
    allow: ["index.php", "*.jpg", "*.jpeg", "*.png", "*.gif", "*.css", "*.js", "*.xml"]
    calculate_etag: true
    weak: false
  middleware: ["static", "gzip"]
  pool:
    debug: true
    num_workers: 2
    max_jobs: 0
    supervisor:
      exec_ttl: 60s

server:
  command: "php public/index.php"
  env_map:
    APP_ENV: "development"
    XDEBUG_MODE: "develop,debug"
    DISPLAY_ERRORS: "1"
    ERROR_REPORTING: "32767"
  relay: "pipes"

logs:
  mode: development
  level: debug
  encoding: console
  output: "/app/public/logs/roadrunner.log"
  err_output: "/app/public/logs/roadrunner_error.log"

reload:
  enabled: true
  patterns: [".php"]
  services:
    http:
      recursive: true
      dirs: ["public"]
      patterns: [".php", ".yaml"]
      ignore: ["vendor"]

health:
  address: "0.0.0.0:2114"
  timeout: 5s

status:
  address: "0.0.0.0:2114"

metrics:
  address: "0.0.0.0:2112"
  collect:
    http_request_duration: true
    http_request_size: true
    http_response_size: true
    php_worker_memory: true
    php_worker_state: true

