services:
  roadrunner:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8070:8069"      # Application
      - "2115:2114"      # Health/Status
      - "2113:2112"      # Metrics
    volumes:
      - ../member:/app/public/member
      - ./logs:/app/logs
      - ./server:/app/server  # Add this line to mount the server directory
    environment:
      - APP_ENV=production
      - TZ=Europe/Vienna
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2115"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

